var app = angular.module('portfolio', []);

app.controller('projects', function($scope) {
   $scope.projects_arr = [
       {title: 'Project1', image: 'images/bla.jpg', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis odio eu mi rhoncus viverra. Maecenas scelerisque nunc sed elit lobortis sodales.', full_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id tortor ut nisi pulvinar consequat. Mauris neque magna, semper a dapibus nec, lobortis et tortor. Cras mauris ipsum, aliquet a est at, dapibusla eget varius congue, neque risus varius elit, vitae auctor nisi turpis in enim. Nam dictum ipsum et lorem commodo, a fermentum neque auctor. Nam eleifend ultrices pharetra. Cras eros enim, efficitur sed nunc in, blandit mattis purus. Nulla dignissim urna id erat consequat, id tempus risus pretium. Mauris venenatis lorem massa, quis porttitor velit dapibus vitae. Aliquam ultrices tortor tellus, at aliquet arcu consequat in.', link: 'https://google.com'},
       {title: 'Project2', image: 'images/bla2.jpg', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis odio eu mi rhoncus viverra. Maecenas scelerisque nunc sed elit lobortis sodales.', full_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id tortor ut nisi pulvinar consequat. Mauris neque magna, semper a dapibus nec, lobortis et tortor. Cras mauris ipsum, aliquet a est at, dapibus auctor purus. In a nibh sit amet nisl hendrerit interdum a sed urna. Nullam imperdiet, tortor vitae feugiat cursus, ante ex laoreet elit, ac placerat urna dolor eu est. Donec vitae odio vitae lorem faucibus consectetur auctor ac velit. Donec tincidunt leo quis consectetur varius. Aenean fermentum vulputate ipsum, a venenatis lacus tincidunt sagittis. M velit dapibus vitae. Aliquam ultrices tortor tellus, at aliquet arcu consequat in.', link: 'https://google.com'},
       {title: 'Project3', image: 'images/bla3.jpg', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis odio eu mi rhoncus viverra. Maecenas scelerisque nunc sed elit lobortis sodales.', full_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id tortor ut nisi pulvinar consequat. Mauris neque magna, semper a dapibus nec, lobortis et tortor. Cras mauris ipsum, aliquet a est at, dapibua. Cras eros enim, efficitur sed nunc in, blandit mattis purus. Nulla dignissim urna id erat consequat, id tempus risus pretium. Mauris venenatis lorem massa, quis porttitor velit dapibus vitae. Aliquam ultrices tortor tellus, at aliquet arcu consequat in.', link: 'https://google.com'},
       {title: 'Project4', image: 'images/bla4.jpg', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis odio eu mi rhoncus viverra. Maecenas scelerisque nunc sed elit lobortis sodales.', full_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id tortor ut nisi pulvinar consequat. Mauris neque magna, semper a dapibus nec, lobortis et tortor. Cras mauris ipsum, aliquet a est at, dapibus auctor purus. In a nibh sit amet nisl hendrerit interdum a sed urna. Nullam imperdiet, tortor vitae feugiat cursus, ante ex laoreet elit, ac placerat urna dolor eu est. Donec vitae odio vitae lorem faucibus consectetur auctor ac velit. Donec tincidunt leo quis consectetur varius. Aenean fermentum vulputate ipsum, a venenatis lacus tincidunt sagittis. Maeceretra. Cras eros enim, efficitur sed nunc in, blandit mattis purus. Nulla dignissim urna id erat consequat, id tempus risus pretium. Mauris venenatis lorem massa, quis porttitor velit dapibus vitae. Aliquam ultrices tortor tellus, at aliquet arcu consequat in.', link: 'https://google.com'},
       {title: 'Project5', image: 'images/bla5.jpg', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis odio eu mi rhoncus viverra. Maecenas scelerisque nunc sed elit lobortis sodales.', full_description: 'Lorem ipsum dolor sit ahendrerit, ligula eget varius congue, neque risus varius elit, vitae auctor nisi turpis in enim. Nam dictum ipsum et lorem commodo, a fermentum neque auctor. Nam eleifend ultrices pharetra. Cras eros enim,natis lorem massa, quis porttitor velit dapibus vitae. Aliquam ultrices tortor tellus, at aliquet arcu consequat in.', link: 'https://google.com'},
       {title: 'Project6', image: 'images/bla6.jpg', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis odio eu mi rhoncus viverra. Maecenas scelerisque nunc sed elit lobortis sodales.', full_description: 'Lorem ipsum d risus pretium. Mauris venenatis lorem massa, quis porttitor velit dapibus vitae. Aliquam ultrices tortor tellus, at aliquet arcu consequat in.', link: 'https://google.com'}
   ] ;
});